# Generated by Django 4.1.3 on 2022-12-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Syllabus', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('ShortDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('IDNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('CRN', models.CharField(max_length=5)),
                ('WhatsaapGroup', models.URLField(null=True)),
                ('RelatedCourse', models.ManyToManyField(to='frontend.course')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes', models.FileField(upload_to='')),
                ('Files', models.FileField(upload_to='')),
                ('Videos', models.FileField(upload_to='')),
                ('Lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='Section',
            field=models.ManyToManyField(to='frontend.section'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('TwitterURL', models.URLField(null=True)),
                ('LinkdinURL', models.URLField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('section', models.ManyToManyField(to='frontend.section')),
            ],
        ),
    ]
