# Generated by Django 4.1.3 on 2022-12-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_instructor_email_alter_instructor_linkdinurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
