# Generated by Django 4.1.3 on 2022-12-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Syllabus',
        ),
    ]
