# Generated by Django 4.1.3 on 2022-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='Syllabus',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
