# Generated by Django 4.1.3 on 2022-12-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='section',
        ),
    ]
