# Generated by Django 4.1.3 on 2022-12-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_instructor_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.instructor'),
        ),
    ]
