# Generated by Django 4.1.3 on 2022-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_section_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
