# Generated by Django 4.1.3 on 2022-12-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('Start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('End_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('Notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
            ],
        ),
    ]
