# Generated by Django 4.1.3 on 2022-12-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
    ]
