# Generated by Django 4.1.3 on 2022-12-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.section'),
        ),
    ]
