# Generated by Django 4.1.3 on 2022-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_material_files_alter_material_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='Fullname',
            field=models.CharField(max_length=300, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='LinkdinURL',
            field=models.URLField(blank=True, null=True, verbose_name='Linkdin URL - Optional'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='TwitterURL',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL - Optional'),
        ),
    ]
