# Generated by Django 4.1.3 on 2022-12-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_instructor_email_alter_instructor_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ShortDescription',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='WhatsaapGroup',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsaap Group'),
        ),
    ]
