# Generated by Django 4.1.3 on 2022-12-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_lecture_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.section'),
        ),
    ]
