# Generated by Django 4.1.3 on 2022-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Section',
        ),
    ]
