# Generated by Django 4.1.3 on 2023-01-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_instructor_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='GithubURL',
            field=models.URLField(blank=True, null=True, verbose_name='Github URL - Optional'),
        ),
    ]
