# Generated by Django 4.1.3 on 2023-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_instructor_fax_instructor_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='GithubURL',
            field=models.URLField(blank=True, null=True, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='LinkdinURL',
            field=models.URLField(blank=True, null=True, verbose_name='Linkdin URL'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='TwitterURL',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
