# Generated by Django 4.1.3 on 2023-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_instructor_address_alter_instructor_githuburl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
