# Generated by Django 4.1.3 on 2023-01-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_instructor_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='RelatedCourse',
        ),
        migrations.AddField(
            model_name='section',
            name='RelatedCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.course'),
        ),
    ]
