# Generated by Django 4.1.3 on 2023-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_remove_section_relatedcourse_course_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Sections',
        ),
        migrations.AddField(
            model_name='course',
            name='Sections',
            field=models.ManyToManyField(to='frontend.section'),
        ),
    ]
