# Generated by Django 4.1.3 on 2023-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_remove_course_sections_course_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Section',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Course',
            field=models.ManyToManyField(to='frontend.course'),
        ),
    ]
