# Generated by Django 4.1.3 on 2023-01-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_remove_lecture_section_lecture_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.course'),
        ),
    ]
