# Generated by Django 4.1.3 on 2023-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='Title',
            field=models.IntegerField(),
        ),
    ]
