# Generated by Django 4.1.3 on 2023-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_alter_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='Title',
            field=models.IntegerField(verbose_name='Lecture Number'),
        ),
    ]
