# Generated by Django 4.1.3 on 2023-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_lecture_date_alter_lecture_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Files',
            new_name='JavaFiles',
        ),
    ]
