# Generated by Django 4.1.3 on 2023-01-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_material_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Form',
            field=models.BooleanField(default=False, verbose_name='Form'),
        ),
    ]
