# Generated by Django 4.1.3 on 2023-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_course_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='Fax',
        ),
        migrations.AddField(
            model_name='instructor',
            name='OfficeHours',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Office Hours'),
        ),
    ]
