# Generated by Django 4.1.3 on 2023-01-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_alter_publication_pdf_alter_publication_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcategories',
            options={'verbose_name': 'Publication Category', 'verbose_name_plural': 'Publication Categories'},
        ),
        migrations.AlterField(
            model_name='material',
            name='Videos',
            field=models.FileField(upload_to=''),
        ),
    ]
